dist: jammy
language: node_js
node_js:
- 18
script:
- bash build.sh
deploy:
  skip_cleanup: true
  on:
    branch: release
  provider: npm
  email: joe.politz@gmail.com
  api_key:
    secure: ZSZx5n2I+Nq3optPiln/r4HSGSPZIS/ey2qQMyhQLG2oEYzd2K/hm3imal/Qjll1evknegUjZ7YMu7Iv0/BBifFZYanO9DfbISfKDBJtJR7CayYVb1Z5go7G41QK5zn2GflhumXsTSN455pQ2fRGwYGY+HsmLi+71z29fEtn2prXkFRee9LGiWfkTn9y611tlX4ZHKcAnLz65B9vVt2noWbFm/fhh0qa9sufTs4wX3FjBoa85fLedXDGYmh5c0NGgSod6fJ20B8xkihF5SPDaiJipNSLTnTUcvI/lrV3uXkF81fOi3emebBwHOZvqQquVzHsQS18D0v00Lfv4riZqglLPVIxY6BVieryGpvykxGiOHcltODjH9Q76ICDc59P+mfVA+iJ95G9dpfL9xZQz46zXr+nUql/pI350NivEq4Cw1yAoK8o4JDzqOZBDMfs8abrkXbGHUkLjc7JhlVE7lNh2Q0oEiF0D8kgYtZe4YCKV/D60sJtQveEMF14CCb6nPgO2kGUizPvYw5Rz+z7kZSGE2R3LvbE5d/+BIZKBkcWDu0FCmNZv0eGtytLfYzG+q/2lcOKNHk22sNSNC+xazDJACaNriEK5Vm6KMTwDcNcoMO4Krw7IMM4WezKN0i6SyPRF52KunIwAPuN12g+uo2kIBkRbwd8/Ok2DpHpofI=
