dist: jammy
language: node_js
node_js:
- 18
script:
- bash build.sh
deploy:
  skip_cleanup: true
  on:
    branch: release
  provider: npm
  email: joe.politz@gmail.com
  api_key:
    secure: MQe6pEmG744T7tTZ3q+Cf9/uqwQOd8TalZO8KWupyPvBWsLokWb53t11HGVitU4ylQTY/BqaSZLzuv0gofExgr8GAdl0OqTz2TikssJXK66dtuyF38/gmOZSjNCTGc2aRadhB7C7aGp7v8bLbjtGSlwHQBSzFGDjYXRTlL7afmN2IQPfmm2Mlib92OsYEnmBpQwCnvAff7DRVJnAH6xQLoczpUbc4Fdq2jfz3JtUbA1ROJnKTfegrMyNTtAr4xPWBa+lYEPj3oDKicaQaslBstGQzUY8AjfqKev5S/BZsWFw/HY1NshTofz4fMMc4d8sYcqxLFN/sklaRL/zkiCGYzp6jhDfFOUxoZuvATCXdcfUdj+2xIG1ti9N7Ib96eNp9cEsh3QUAeRK69u7OITUdHly4sTAy5JTlXcRz82Aa2wtruE/3fcdhv0it9nVfQyVAYz46C5PAfSjBb2mD8OzxXJpjqOLs43vavko49/ryLSyoWLEKlVFz92TUAiHCwgL3Qz3PisrSivUwPzLxitBUbmNn8DSJ7UybaoacuPTbBY7Hq09XyJQ4MTfhmOqI2/IsyiszPZ4n+9Swtg2O+voPneJagc6YnI4d+PmfDK0Nz6Wjwd8f4N5HY0TJKl6UlZPlKb0ohmlimZSjW+EzrvuI2pcs7G0CsxY61bOkLs8JDo=
