dist: jammy
language: node_js
node_js:
- 18
script:
- bash build.sh
deploy:
  skip_cleanup: true
  on:
    branch: release
  provider: npm
  email: joe.politz@gmail.com
  api_key:
    secure: HD0cwnihqdMUqaXkCzvPHuwNAJ5+p1kUmme1f7xNgXAfYqn/s9fj1ym4el8gautCPoaB7dV5pXG3DyJ0iqJxrWm02bM1KHy7wGrDwY83wbxbWkYfpjTObd+pheQIF3h57cbl8QX1o8wQq3+K0sF4XvynGR/DjZEagTmgyemIOZzVNQRtaWiFxH/C5X2tjlWzXpSAuaUhxlWBeUZLAsb0HberHGN0vltXBccY2Ts0GIXBzN3QLK93AwD2PJeDVZ8+8I9VPTbX7K9LSUlXHZ8onFxSHgHVSVcuUEr5UKT7VeUMGkkW7FegH5qf4HnfclKrJOhbBSth0v6mQMbqFTiW5Fi4PQFvxHP/AVI2+Ne9Bv1Ym+t5yGAAVH6QSdJd2JBe+CW78ajn43ATZKPyI542T6r7jiqGEzx1QrHcOCFzM0sas3vRjyjx8Q7j+SL3G46R3qg5YxShggpqgcm7B/tY9bx+GI7nm0ioL9laoPNncOBhBOYUDQl8tStL09XIf668uIy/Rd17UziAaUuF61OIZxDAX5CVVQ9YWXsxZWBLVauxXK1Uf4mQEbcP/nUjk9mFkGjZHaterzF/yq5yUoA2CmPEiivKUvqZYPZcFkM+6sEOMbHjk+GW++uD79UqyNdJ37wFONgk8iNzbo89u11LGE6MLup7s0YBlDQriV/fpUs=
