dist: jammy
language: node_js
node_js:
- 18
script:
- bash build.sh
deploy:
  skip_cleanup: true
  on:
    branch: release
  provider: npm
  email: joe.politz@gmail.com
  api_key:
    secure: "L9yBu/F7D9cRF3vskTB62XEjSuDUDzzKBoAlZdKTCyzwE2gOXarYNFeT+/JKw5LXLlQRWIzj+GAN3/qIogKGN08YdaGpOqcIq4R6UYcGnwXJqr+SWifZhNbAgF9e5sVi4p793X2/XLVe5UGh1bhBGVw8l7Xx9LOWHMbK1REYJhVIIXNHrFY1HmPJKOZW3kTiuccwYDRDkO3WwB3TCHm9ne4FCaWi0juWV9BQjFQMWa9eqSyO4PIBdRWymqYYQyOtZqiWeOMdpwAsipAsJtZ7Y6FhM7PoLiKq+8CLqcb9+LHFp0LyLf4erPO9F224bMJkLgRQyO/gi1KZ1BDEdsKeRh+dE/nWFdu5Cz0+GdbsC/UDLW8xljNULTGVset1rWBtgmiPzsDlcA1VdLxeUfQAVQqC+WJH8ZelcWJ/K9unTHSXKyXAYYDFt2vNEl5G1SSfgArgmi/0VF6dAcappHij68H+ct7ci1lgjnfO/NSmTeebzmOdv0kRPo2O8UQEMHvtcI/ClFbyGJOv23FjGlq5e5MyLsX5WCEyBmgMzqzSWeq11/HAbYd706HsRbkhJLyoCl2o1NUmkkDN607lj/mnJEQUmaVr7jlIR/my6vZKmj97xsp9fkjkwPniPcdIfBmACbOpj3T7KmuXVevRhW/lqsJQEjODFIhpefg1M5O+PI4="
